name: Build HookCase & NootedGreen
on:
  workflow_dispatch

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 编译 HookCase，目录 HookCase-master
      - name: Build HookCase
        run: |
          cd HookCase-master
          xcodebuild -project HookCase.xcodeproj -scheme HookCase -configuration Release build

      # 编译 NootedGreen
      - name: Build NootedGreen
        run: |
          xcodebuild -project NootedGreen.xcodeproj -scheme NootedGreen -configuration Release build

      # 收集产物
      - name: Collect Kexts
        run: |
          mkdir Output
          cp -r HookCase-master/build/Release/HookCase.kext Output/
          cp -r NootedGreen/build/Release/NootedGreen.kext Output/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Compiled_Kexts
          path: Output/
